### ISSUE TITLE
How to flat field correct one image?

### ISSUE THREAD

**Issue by sleepingcat4** [schuetzgroup/sdt-python#7]
I went through the documentation and saw I require two images to perform flat fielding whereas I only have one image and I want to perform flat fielding on that image only. Can someone help me knowing if it is possible with ```sdt-python``` python library or not. 

referring to this documentation: https://schuetzgroup.github.io/sdt-python/flatfield.html

**Comment by lschr** [comment]
Yes, you can also create the `flatfield.Corrector` object with a single image only.

The example in the documentation demonstrates how to use multiple images (or image series), from which an average is calculated for flatfield correction. This works as well for a single image, in which case the average is just the image.

**Comment by lschr** [comment]
In order to perform the flatfield correction, the first step is to determine the spatial correction function $c(x, y)$. For microscopy images, this can, for instance, be derived from images of a homogeneous sample. By creating a `flatfield.Corrector` instance, $c(x, y)$ is computed. How this is done, depends on your use case; either by 

- using the image as is or
- averaging several images or
- fitting a 2D Gaussian to the image or
- if you have single-molecule intensity data instead of an image, by fitting a 2D Gaussian to  single-molecule intensities

The image can additionally be smoothed to get rid of local disturbances.

The second step is to apply $c(x, y)$ to the image (or single-molecule data) to be corrected. This is done by using the `flatfield.Corrector` instance like a function (i.e., calling `flatfield.Corrector.__call__)`.

Could you share some information about your use case? Maybe some data as well? That would make it easier to help.

**Comment by sleepingcat4** [comment]
![Image_T0000_C0000_X0000_Y0000_Z1000](https://github.com/schuetzgroup/sdt-python/assets/81933585/abd3e1eb-6e74-4ce5-aca1-3e5ab7013d24)

this is one of the sample images. I am merging these images (monatge) to receive the final resampled image. I want to do flat fielding in these small images. Do you have any idea, what method will be well-suited? @lschr

**Comment by lschr** [comment]
Hmmm, I am not sure if the flatfield module here can help. It is intended to correct for illumination intensity differences across the field of view (typically a fall-off towards the edges) in microscopy images, as in the example below,
![image](https://github.com/schuetzgroup/sdt-python/assets/13418822/6e41bfb4-d154-4b80-8d6b-a6b9ab0183f0)

In your image, there is this sharp edge. You'd probably need to blur it with a filter that preserves this edge, but smears out the small details to determine the lighting intensity. Maybe it can be done with OpenCV, but I have no experience in this regard.

**Comment by sleepingcat4** [comment]
I think I can apply a combination of medianBlur and flat fielding. I'm unsure how your library does flatfield over SimpleITK. Since SimpleITK uses a N4BiasFlatfielding and I have seen it does produce good results if I can separate background and foreground properly.

**Comment by lschr** [comment]
I am afraid such a thing is out of scope. The idea of `sdt.flatfield.Corrector` is to feed it (typically measured) flatfield frames and make subsequent correction easy.

You can of course use the result from the SimpleITK algorithm as input for `sdt.flatfield.Corrector` and then correct your data with it.
